<?php
/**
 * Created by PhpStorm.
 * User: sooglejay
 * Date: 17/12/2
 * Time: 17:49
 */

namespace TSS;
require_once dirname(__FILE__).'/../util/AppUtil.php';
class MainModel extends AppUtil
{
    public function getWeekIdByTime($time)
    {
        return parent::getWeekIdByTime($time); // TODO: Change the autogenerated stub
    }

}